from pyairctrl.subset_enum import subsetEnum

STATUS_TRANSFORMER = {
    "name": {
        "fieldname": "Name",
        "rawDescription": None,
        "transformDescription": None,
        "subsets": [subsetEnum.status, subsetEnum.firmware],
        "transform": None,
    },
    "type": {
        "fieldname": "Type",
        "rawDescription": None,
        "transformDescription": None,
        "subsets": [subsetEnum.status],
        "transform": None,
    },
    "modelid": {
        "fieldname": "ModelId",
        "rawDescription": None,
        "transformDescription": None,
        "subsets": [subsetEnum.status],
        "transform": None,
    },
    "swversion": {
        "fieldname": "Version",
        "rawDescription": None,
        "transformDescription": None,
        "subsets": [subsetEnum.status, subsetEnum.firmware],
        "transform": None,
    },
    "StatusType": {
        "fieldname": "StatusType",
        "rawDescription": None,
        "transformDescription": None,
        "subsets": [subsetEnum.status],
        "transform": None,
    },
    "ota": {
        "fieldname": "Over the air updates",
        "rawDescription": None,
        "transformDescription": None,
        "subsets": [subsetEnum.status, subsetEnum.firmware],
        "transform": None,
    },
    "Runtime": {
        "fieldname": "Runtime",
        "rawDescription": "in ms",
        "transformDescription": "in h",
        "subsets": [subsetEnum.status],
        "transform": lambda runtime: round(runtime / (1000 * 60 * 60), 2),
    },
    "pwr": {
        "fieldname": "Power",
        "rawDescription": None,
        "transformDescription": None,
        "subsets": [subsetEnum.status],
        "transform": lambda pwr: {"1": "ON", "0": "OFF"}.get(pwr, pwr),
    },
    "pm25": {
        "fieldname": "PM25",
        "rawDescription": None,
        "transformDescription": None,
        "subsets": [subsetEnum.status],
        "transform": None,
    },
    "rh": {
        "fieldname": "Humidity",
        "rawDescription": None,
        "transformDescription": None,
        "subsets": [subsetEnum.status],
        "transform": None,
    },
    "rhset": {
        "fieldname": "Target humidity",
        "rawDescription": None,
        "transformDescription": None,
        "subsets": [subsetEnum.status],
        "transform": None,
    },
    "iaql": {
        "fieldname": "Allergen index",
        "rawDescription": None,
        "transformDescription": None,
        "subsets": [subsetEnum.status],
        "transform": None,
    },
    "tvoc": {
        "fieldname": "Total volatile organic compounds",
        "rawDescription": None,
        "transformDescription": None,
        "subsets": [subsetEnum.status],
        "transform": None,
    },
    "temp": {
        "fieldname": "Temperature",
        "rawDescription": None,
        "transformDescription": None,
        "subsets": [subsetEnum.status],
        "transform": None,
    },
    "func": {
        "fieldname": "Function",
        "rawDescription": None,
        "transformDescription": None,
        "subsets": [subsetEnum.status],
        "transform": lambda func: {
            "P": "Purification",
            "PH": "Purification & Humidification",
        }.get(func, func),
    },
    "mode": {
        "fieldname": "Mode",
        "rawDescription": None,
        "transformDescription": None,
        "subsets": [subsetEnum.status],
        "transform": lambda mode: {
            "P": "auto",
            "A": "allergen",
            "S": "sleep",
            "M": "manual",
            "B": "bacteria",
            "N": "night",
            "T": "turbo",
            "GT": "gentle",
        }.get(mode, mode),
    },
    "om": {
        "fieldname": "Fan speed",
        "rawDescription": None,
        "transformDescription": None,
        "subsets": [subsetEnum.status],
        "transform": lambda om: {"s": "silent", "t": "turbo", "a": "auto"}.get(om, om),
    },
    "aqil": {
        "fieldname": "Light brightness",
        "rawDescription": None,
        "transformDescription": None,
        "subsets": [subsetEnum.status],
        "transform": None,
    },
    "aqit": {
        "fieldname": "Air quality notification threshold",
        "rawDescription": None,
        "transformDescription": None,
        "subsets": [subsetEnum.status],
        "transform": None,
    },
    "uil": {
        "fieldname": "Buttons light",
        "rawDescription": None,
        "transformDescription": None,
        "subsets": [subsetEnum.status],
        "transform": lambda uil: {"1": "ON", "0": "OFF"}.get(uil, uil),
    },
    "ddp": {
        "fieldname": "Used index",
        "rawDescription": None,
        "transformDescription": None,
        "subsets": [subsetEnum.status],
        "transform": None,
    },
    "wl": {
        "fieldname": "Water level",
        "rawDescription": None,
        "transformDescription": None,
        "subsets": [subsetEnum.status],
        "transform": None,
    },
    "cl": {
        "fieldname": "Child lock",
        "rawDescription": None,
        "transformDescription": None,
        "subsets": [subsetEnum.status],
        "transform": None,
    },
    "dt": {
        "fieldname": "Timer",
        "rawDescription": "in h",
        "transformDescription": "in h - only if >0",
        "subsets": [subsetEnum.status],
        "transform": lambda dt: None if dt == 0 else dt,
    },
    "dtrs": {
        "fieldname": "Timer left",
        "rawDescription": "in minutes",
        "transformDescription": "in minutes - only if >0",
        "subsets": [subsetEnum.status],
        "transform": lambda dtrs: None if dtrs == 0 else dtrs,
    },
    "fltt1": {
        "fieldname": "HEPA filter type",
        "rawDescription": None,
        "transformDescription": None,
        "subsets": [subsetEnum.status],
        "transform": lambda fltt1: {"A3": "NanoProtect Filter Series 3 (FY2422)"}.get(
            fltt1, fltt1
        ),
    },
    "fltt2": {
        "fieldname": "Active carbon filter type",
        "rawDescription": None,
        "transformDescription": None,
        "subsets": [subsetEnum.status],
        "transform": lambda fltt2: {"C7": "NanoProtect Filter AC (FY2420)"}.get(
            fltt2, fltt2
        ),
    },
    "fltsts0": {
        "fieldname": "Pre-filter and Wick - replace time",
        "rawDescription": "in h",
        "transformDescription": "in h",
        "subsets": [subsetEnum.status, subsetEnum.filter],
        "transform": None,
    },
    "fltsts1": {
        "fieldname": "HEPA filter - replace time",
        "rawDescription": "in h",
        "transformDescription": "in h",
        "subsets": [subsetEnum.status, subsetEnum.filter],
        "transform": None,
    },
    "fltsts2": {
        "fieldname": "Active carbon filter - replace time",
        "rawDescription": "in h",
        "transformDescription": "in h",
        "subsets": [subsetEnum.status, subsetEnum.filter],
        "transform": None,
    },
    "wicksts": {
        "fieldname": "Wick filter - replace time",
        "rawDescription": "in h",
        "transformDescription": "in h",
        "subsets": [subsetEnum.status, subsetEnum.filter],
        "transform": None,
    },
    "err": {
        "fieldname": "Error",
        "rawDescription": None,
        "transformDescription": "None, if err = 0",
        "subsets": [subsetEnum.status],
        "transform": lambda err: None
        if err == 0
        else {
            193: "F0 (pre-filter) must be cleaned",
            49408: "no water",
            32768: "water tank open",
            49155: "pre-filter must be cleaned",
        }.get(err, err),
    },
    "cppid": {
        "fieldname": "Device ID",
        "rawDescription": None,
        "transformDescription": "None",
        "subsets": [subsetEnum.wifi],
        "transform": None,
    },
    "dhcp": {
        "fieldname": "DHCP active",
        "rawDescription": None,
        "transformDescription": "None",
        "subsets": [subsetEnum.wifi],
        "transform": None,
    },
    "gateway": {
        "fieldname": "Gateway Address",
        "rawDescription": None,
        "transformDescription": "None",
        "subsets": [subsetEnum.wifi],
        "transform": None,
    },
    "ipaddress": {
        "fieldname": "IP Address",
        "rawDescription": None,
        "transformDescription": "None",
        "subsets": [subsetEnum.wifi],
        "transform": None,
    },
    "macaddress": {
        "fieldname": "Mac Address",
        "rawDescription": None,
        "transformDescription": "None",
        "subsets": [subsetEnum.wifi],
        "transform": None,
    },
    "netmask": {
        "fieldname": "Netmask",
        "rawDescription": None,
        "transformDescription": "None",
        "subsets": [subsetEnum.wifi],
        "transform": None,
    },
    "password": {
        "fieldname": "Password",
        "rawDescription": None,
        "transformDescription": "None",
        "subsets": [subsetEnum.wifi],
        "transform": None,
    },
    "protection": {
        "fieldname": "Protection level",
        "rawDescription": None,
        "transformDescription": "None",
        "subsets": [subsetEnum.wifi],
        "transform": None,
    },
    "ssid": {
        "fieldname": "SSID",
        "rawDescription": None,
        "transformDescription": "None",
        "subsets": [subsetEnum.wifi],
        "transform": None,
    },
    "mandatory": {
        "fieldname": "Mandatory",
        "rawDescription": None,
        "transformDescription": "None",
        "subsets": [subsetEnum.firmware],
        "transform": None,
    },
    "progress": {
        "fieldname": "Firmware progress",
        "rawDescription": None,
        "transformDescription": "None",
        "subsets": [subsetEnum.firmware],
        "transform": None,
    },
    "state": {
        "fieldname": "Firmware state",
        "rawDescription": None,
        "transformDescription": "None",
        "subsets": [subsetEnum.firmware],
        "transform": None,
    },
    "statusmsg": {
        "fieldname": "Firmware message",
        "rawDescription": None,
        "transformDescription": "None",
        "subsets": [subsetEnum.firmware],
        "transform": None,
    },
    "upgrade": {
        "fieldname": "Firmware upgrade",
        "rawDescription": None,
        "transformDescription": "None",
        "subsets": [subsetEnum.firmware],
        "transform": None,
    },
    "version": {
        "fieldname": "Firmware version",
        "rawDescription": None,
        "transformDescription": "None",
        "subsets": [subsetEnum.firmware],
        "transform": None,
    },
}